### ISSUE TITLE
Change header import in sagemaker example 

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/data-science-examples#57]
As mentioned [here](https://github.com/exasol/data-science-examples/pull/56#discussion_r1186215021), we directly import of the header of the scania trucks data set into exasol at the moment, and as a result use
`all_columns = exasol.export_to_pandas("SELECT * FROM IDA.TRAIN LIMIT 1;")` 
for the reading of the header, which is not great.

please update in the three files mentioned below by using [this](https://docs.exasol.com/saas/sql_references/system_tables/metadata/exa_user_columns.htm) or [this](https://docs.exasol.com/db/latest/sql/desc[ribe].htm):

we import the data using [this notebook from sagemaker tutorial](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/sagemaker/LoadExampleDataIntoExasol.ipynb) for the data import which needs to be changed, and then the data is read in the [sagemaker tutorial](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/sagemaker/TrainSagemakerModelWithExasolData.ipynb) and in the [azureml tutorial](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/AzureML/ConnectAzureMLtoExasol.ipynb)

**Comment by tkilias** [comment]
Closing, because repo gets archived
