### ISSUE TITLE
Remove mentiones of wrong file path bug 

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/data-science-examples#59]
Currently there is a bug in the saas online interface where the path of bucketfs files is shown incorrectly. this is mentioned in the [azureml tutorial](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/AzureML/InvokeModelFromExasolDBwithUDF.ipynb). once this bug is fixed, remove the two mentions of it.

**Comment by tkilias** [comment]
Closing, because repo gets archived
