### ISSUE TITLE
Use connection for BucketFS information in classification examples

### ISSUE THREAD

**Issue by tkilias** [exasol/data-science-examples#9]
Currently, the BucketFS connection information get embedded into the UDF code ([classification.ipynb](https://github.com/exasol/data-science-examples/blob/main/tutorials/machine-learning/python/scikit-learn/classification.ipynb)). A much cleaner method is, to provide this information via a connection. Either, by providing the BucketFS URL directly, or by providing a path to a configuration file in the BucketFS. 

- In order to upload an object into BucketFS, the notebook creates and uses an UDF called _EXABUCKET_HELPER_. 
- Then this UDF is called when an object is going to be uploaded. Instead of creating an UDF to upload an object into BucketFS, we can use bucketfs connection object and bucketfs_python libraries.

**Comment by redcatbear** [comment]
@umitbuyuksahin, which sample are we talking about in detail.

**Comment by tkilias** [comment]
Closing, because repo gets archived
